default: &default
  adapter: postgresql
  encoding: unicode
  login: bruno
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_maino_development

test:
  <<: *default
  database: blog_maino_test

production:
  <<: *default
  database: blog_maino_production
  username: blog_maino
  password: <%= ENV["BLOG_MAINO_DATABASE_PASSWORD"] %>
